apiVersion: apollographql.com/v1alpha1
kind: Subgraph
metadata:
  name: products
  labels:
    domain: retail
  namespace: apollo-operator
spec:
  endpoint: http://reviews
  schema:
    oci:
      reference: ghcr.io/jonathanrainer/reviews:latest
