apiVersion: apollographql.com/v1alpha1
kind: Supergraph
metadata:
  name: retail
spec:
  replicas: 2
  schema:
    resource:
      name: retail
  routerConfig:
    homepage:
      enabled: false
    sandbox:
      enabled: true
    supergraph:
      introspection: true
  podTemplate:
    routerVersion: 2.5.0
