apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator
  namespace: argocd
spec:
  project: default
  source:
    chart: operator-chart
    repoURL: registry-1.docker.io/apollograph
    targetRevision: *
    helm:
      releaseName: apollo-operator
  destination:
    server: "https://kubernetes.default.svc"
    namespace: apollo-operator
  syncPolicy:
    automated: { }